services:
  geo:
    image: '49778b0fa113'
    container_name: geo
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: 'redis'
    container_name: redis
    expose:
      - '6379'